# Generated by Django 4.0 on 2021-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('health', models.IntegerField()),
                ('health_regen', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('abilities', models.TextField()),
            ],
        ),
    ]
