# Generated by Django 4.0 on 2021-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0002_survivor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
