# Generated by Django 4.0 on 2021-12-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0003_remove_item_id_remove_survivor_id_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('items', models.ManyToManyField(to='RoRplanner.Item')),
                ('survivors', models.ManyToManyField(to='RoRplanner.Survivor')),
            ],
        ),
    ]
