# Generated by Django 4.0 on 2021-12-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0004_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='armor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='health',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='health_regen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='speed',
            field=models.FloatField(),
        ),
    ]
