# Generated by Django 4.0 on 2021-12-09 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0006_build_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
