# Generated by Django 4.0 on 2021-12-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0007_build_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='items',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='abilities',
        ),
        migrations.AddField(
            model_name='build',
            name='always_avoid_items',
            field=models.ManyToManyField(related_name='always_avoid_in_builds', to='RoRplanner.Item'),
        ),
        migrations.AddField(
            model_name='build',
            name='recommended_items',
            field=models.ManyToManyField(related_name='recommended_in_builds', to='RoRplanner.Item'),
        ),
        migrations.AddField(
            model_name='build',
            name='required_items',
            field=models.ManyToManyField(related_name='required_in_builds', to='RoRplanner.Item'),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('proc_coefficient', models.FloatField()),
                ('cooldown', models.FloatField()),
                ('type', models.SmallIntegerField(choices=[(0, 'Passive'), (1, 'Primary'), (2, 'Secondary'), (3, 'Utility'), (4, 'Special')])),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoRplanner.survivor')),
            ],
        ),
    ]
