# Generated by Django 4.0 on 2021-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0008_remove_build_items_remove_survivor_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='proc_coefficient',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='always_avoid_items',
            field=models.ManyToManyField(blank=True, related_name='always_avoid_in_builds', to='RoRplanner.Item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='recommended_items',
            field=models.ManyToManyField(blank=True, related_name='recommended_in_builds', to='RoRplanner.Item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='required_items',
            field=models.ManyToManyField(blank=True, related_name='required_in_builds', to='RoRplanner.Item'),
        ),
    ]
