# Generated by Django 4.0 on 2021-12-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0010_alter_ability_cooldown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
