# Generated by Django 4.0 on 2021-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoRplanner', '0011_alter_build_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='required_items',
            field=models.ManyToManyField(related_name='required_in_builds', to='RoRplanner.Item'),
        ),
    ]
