# Generated by Django 4.0 on 2021-12-15 17:55

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('RoRplanner', '0012_alter_build_required_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='creator',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
