# Generated by Django 4.0 on 2021-12-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('RoRplanner', '0013_alter_build_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
